### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by favonia**
@BowenWang @hawnzug I wonder if you are fine with this license. Please let me know!

### CODE REVIEW

**Review by hawnzug — APPROVED** [review]
I'm fine with it.

**Comment by BowenWang** [comment]
Sorry I just saw this email, I am fine with it.

-- Bowen

**Comment by favonia** [comment]
@BowenWang It will help me track the record by "approving" the changes. Thanks!

**Comment by favonia** [comment]
@norileo @mahrud Please indicate that you are fine with the license.

@remexre According to #11, I suppose you meant you agreed with the license. :-)

**Review by remexre — APPROVED** [review]
yep!

**Review by norileo — APPROVED** [review]

**Pull request merged**
