### PR TITLE
Add the instruction about newtx. Close #3.

### LINKED ISSUE #3: Missing `references.bib` and `txex-bar`
1. `references.bib`, referenced in `hdtt2020.sty` and presumably including the reference to `hott-as:book`, is missing.

2. I ran into an issue where the `latex` command worked fine, but `pdflatex` complained at a certain `txex-bar` file being missing:
```
kpathsea: Running mktextfm txex-bar
/usr/share/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for txex-bar.
/usr/share/texlive/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input txex-bar
This is METAFONT, Version 2.7182818 (TeX Live 2018) (preloaded base=mf)


kpathsea: Running mktexmf txex-bar
! I can't find file `txex-bar'.
```

In case anyone else has this issue, the solution was to install the `newtx` package (i.e., in addition to `newpx`).

### PR DESCRIPTION
**Pull request by favonia**
Close #3.

### CODE REVIEW

**Comment by favonia** [comment]
@mahrud Do you think this solves the problem?

**Review by mahrud — APPROVED** [review]

**Comment by mahrud** [comment]
Yes, thank you!

**Comment by jonsterling** [comment]
For most users, it might be more clear to suggest that people install a current distribution of TeX (such as TeXLive 2019); installing specific TeX packages (as opposed to upgrading the distribution) is not very user-friendly and is long-term kind of a recipe for disaster.

**Comment by favonia** [comment]
@mahrud I was actually wondering about that, too. How did you install the TeX packages? Are you using some TeX distribution and somehow newtx was not automatically installed?

**Comment by mahrud** [comment]
I'm using `texlive-2018`, which is the latest version packaged for Fedora
30 and `texlive-newtx` is not automatically installed (same with almost all
optional texlive packages). For all other latex package requirements,
`latex` warns that `blahblah.sty` is missing, so you'd know to install
this. However there is no message indicating that `newtx` is missing, so it
required some investigation to see what package this missing file belongs
to.

Might be simpler to remove `newpx` if this is an issue.

**Comment by favonia** [comment]
I took a look and felt `newpx` and `newtx` is still the packages that pay most attention to kerning. I think we can afford an extra installation step. To be honest, I wonder why the Fedora team did not fix the dependency issue brought up in https://bugzilla.redhat.com/show_bug.cgi?id=1047992, and only mentioned that newtx was required in its description (see https://www.rpmfind.net/linux/RPM/opensuse/tumbleweed/noarch/texlive-newpx-2019.168.1.33svn49438-42.1.noarch.html). Debian and Arch-based systems package all these packages as `fontextra` and avoided the issue.

**Pull request merged**
