### PR TITLE
Cite van den berg and garner

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Review by favonia — APPROVED** [review]
Thanks! Maybe we should cite https://arxiv.org/abs/0812.0409 too.

**Comment by jonsterling** [comment]
Good point! Those two papers were written simultaneously, based on independent research.

**Comment by jonsterling** [comment]
I have added the citation to Peter's paper

**Comment by jonsterling** [comment]
P.S. I found that it is very very very difficult to edit these notes because 99% of each filename is the same as the others. I suggest finding a better scheme for naming the .tex files.

**Pull request merged**
